// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT9jS7ddJmefeIJ5g9wGZYTltjIbBMaVg',
    appId: '1:426433137402:web:b432acb7d52f5cd2135743',
    messagingSenderId: '426433137402',
    projectId: 'smartfab-tracker-d2ea8',
    authDomain: 'smartfab-tracker-d2ea8.firebaseapp.com',
    storageBucket: 'smartfab-tracker-d2ea8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiAoLbbrIh7jZ75sYJmfHJWf-eP1J2fCo',
    appId: '1:426433137402:android:e2c1ffc7cdee934c135743',
    messagingSenderId: '426433137402',
    projectId: 'smartfab-tracker-d2ea8',
    storageBucket: 'smartfab-tracker-d2ea8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVy5zIdSH5vogmwzLes_Lv-OmPOSuJDCw',
    appId: '1:426433137402:ios:d772a92bfe540421135743',
    messagingSenderId: '426433137402',
    projectId: 'smartfab-tracker-d2ea8',
    storageBucket: 'smartfab-tracker-d2ea8.firebasestorage.app',
    iosBundleId: 'com.example.smartfabApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVy5zIdSH5vogmwzLes_Lv-OmPOSuJDCw',
    appId: '1:426433137402:ios:d772a92bfe540421135743',
    messagingSenderId: '426433137402',
    projectId: 'smartfab-tracker-d2ea8',
    storageBucket: 'smartfab-tracker-d2ea8.firebasestorage.app',
    iosBundleId: 'com.example.smartfabApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT9jS7ddJmefeIJ5g9wGZYTltjIbBMaVg',
    appId: '1:426433137402:web:405902c0b2e7e127135743',
    messagingSenderId: '426433137402',
    projectId: 'smartfab-tracker-d2ea8',
    authDomain: 'smartfab-tracker-d2ea8.firebaseapp.com',
    storageBucket: 'smartfab-tracker-d2ea8.firebasestorage.app',
  );
}
